# DO NOT MODIFY SCENARIOS
# These .feature files define expected behavior derived from requirements.
# During implementation:
#   - Write step definitions to match these scenarios
#   - Fix code to pass tests, don't modify .feature files
#   - If requirements change, re-run /iikit-04-testify

@US-7
Feature: 13-Page Sitemap Shell
  The site has exactly 13 canonical pages, a validated sitemap.xml, correct
  301 redirects for legacy URLs, a primary nav with 5 items + 1 CTA + 3 toggles,
  and a footer listing all 12 public pages.

  # ── Acceptance Tests (from spec.md US-7) ──

  @TS-052 @FR-080 @SC-016 @P1 @acceptance
  Scenario: Sitemap.xml contains exactly 12 URL entries
    Given sitemap.xml is generated by "scripts/generate-sitemap-xml.js"
    When it is parsed
    Then it contains exactly 12 <url> entries

  @TS-053 @FR-080 @P1 @acceptance
  Scenario: Legacy /vision.html redirects to /metodo/
    Given a GET request to "/vision.html"
    Then the response is 301 with Location "/metodo/"

  @TS-054 @FR-080 @P1 @acceptance
  Scenario: Legacy /servicios/ redirects to /programas/
    Given a GET request to "/servicios/"
    Then the response is 301 with Location "/programas/"

  @TS-055 @FR-080 @P1 @acceptance
  Scenario: Legacy /ruta/ redirects to /diagnostico/
    Given a GET request to "/ruta/"
    Then the response is 301 with Location "/diagnostico/?utm_source=legacy-ruta"

  @TS-056 @FR-080 @P1 @acceptance
  Scenario: 404 page renders shell with home button
    Given a GET request to "/nonexistent"
    Then the response is 404
    And the body renders the "404.html" shell with a "Volver al home" button

  @TS-057 @FR-080 @P1 @acceptance
  Scenario: Primary nav has correct structure
    Given the primary nav is rendered
    When inspected
    Then it contains exactly 5 nav items + 1 CTA button + 3 toggles

  @TS-058 @FR-080 @P1 @acceptance
  Scenario: Footer lists all 12 public pages
    Given the footer is rendered
    When inspected
    Then it lists the 12 public pages

  # ── Validation Tests ──

  @TS-059 @FR-080 @SC-016 @P1 @validation
  Scenario: Canonical page count is exactly 13
    Given the physical page count (index.html + 404.html under root, excluding dist/ and node_modules/)
    When counted by "scripts/count-pages.js"
    Then the count is exactly 13
