"""
Expansion module for Biblioteca Universal v4.
Contains the remaining ~239 SPECs to reach 443 total.
Categories: visual, agentes, stack, automatizacion, engine, solucion,
presentacion, comunicacion, decision, liderazgo, aprendizaje,
negociacion, creatividad, bienestar, estrategia, meta + gaps.
"""

def register_expansion(qspec):
    """Register all expansion SPECs using the qspec helper from build_library_v4."""

    # ─── VISUAL GAPS (+7) ───

    qspec("visual_paleta_colores_profesional", "Para seleccionar una paleta de colores que comunique la personalidad correcta y funcione en todos los medios. El color es el primer mensaje que recibe tu audiencia.", "Disenador de Color y Brand Strategist con experiencia en color psychology aplicada a marcas premium y sistemas de diseno.", """Paleta profesional:\n1. Analizar personalidad de marca: que emociones comunicar\n2. Color primario: 1 color protagonista con justificacion psicologica\n3. Color secundario: 1 complemento con contraste optimo\n4. Acentos: 1-2 colores de enfasis para CTAs y highlights\n5. Neutros: gama de grises para texto, fondos, bordes\n6. Accesibilidad: verificar ratios WCAG AA/AAA\n7. Paleta completa con hex, RGB, HSL""", "Metodo:\n- Color psychology: red=urgencia, blue=confianza, gold=premium\n- 60-30-10 rule: 60% neutro, 30% primario, 10% acento\n- Contrast checker: WCAG AA minimo (4.5:1 para texto)\n- Cross-media: la paleta debe funcionar en screen, print, y dark mode", "Formato: paleta completa con codigos + guia de uso + accesibilidad.\nTono: creativo-tecnico.\nAudiencia: disenador o profesional que define su identidad visual.\nAccion: aplicar la paleta a todos los canales.", ["El color primario tiene justificacion psicologica", "Los ratios de contraste pasan WCAG AA", "La paleta tiene max 6 colores (no 20)", "Funciona en light mode y dark mode"], [{'name': 'MARCA', 'desc': 'Marca o proyecto'}, {'name': 'PERSONALIDAD', 'desc': '3 adjetivos que definen la marca'}, {'name': 'SECTOR', 'desc': 'Sector o industria', 'opt': True}])

    qspec("visual_diseno_social_media_kit", "Para crear un kit de templates para redes sociales que mantenga consistencia visual en todas las publicaciones. La consistencia visual es reconocimiento de marca.", "Social Media Designer con experiencia en creacion de kits visuales para marcas B2B y B2C en Instagram, LinkedIn y TikTok.", """Social Media Kit:\n1. Grid de formatos: post (1080x1080), story (1080x1920), carousel, reel cover\n2. Template por tipo de contenido: quote, tip, dato, case, CTA\n3. Guia tipografica: fonts, tamanos, jerarquias\n4. Paleta aplicada: como se usan los colores en cada formato\n5. Elementos recurrentes: marcos, iconos, watermark\n6. Specs para herramienta de diseno (Canva, Figma)""", "Metodo:\n- Template > freestyle: la consistencia gana al genio esporadico\n- Platform-native sizes: cada red tiene sus formatos\n- Brand recognition: 3 elementos recurrentes que hagan reconocible\n- Batch-friendly: templates pensados para produccion rapida", "Formato: specs de templates por formato + guia de uso.\nTono: creativo-sistematico.\nAudiencia: community manager o creador de contenido.\nAccion: crear los templates en Canva o Figma.", ["Los formatos cubren las 3 plataformas principales", "Los templates cubren 5+ tipos de contenido", "La guia tipografica tiene jerarquia clara", "Los specs son implementables en la herramienta elegida"], [{'name': 'MARCA', 'desc': 'Marca o perfil'}, {'name': 'PLATAFORMAS', 'desc': 'Redes sociales activas'}, {'name': 'PALETA', 'desc': 'Colores de marca (hex codes)', 'opt': True}])

    qspec("visual_presentacion_minimalista", "Para crear presentaciones donde cada slide dice mas con menos. El minimalismo en presentaciones no es vacio — es enfoque absoluto en el mensaje.", "Presentation Minimalist con experiencia en keynotes de alto impacto (estilo Apple, TED) donde cada pixel tiene proposito.", """Presentacion minimalista:\n1. 1 idea por slide — sin excepciones\n2. Max 10 palabras por slide (el speaker dice el resto)\n3. Visual dominante: imagen, numero o diagrama que cuenta la historia\n4. Fondo limpio: max 2 colores por slide\n5. Transiciones: corte seco (no dissolve, no fly-in)\n6. Slide-by-slide spec con visual + nota del speaker""", "Metodo:\n- Apple keynote style: imagen grande, texto minimo\n- Takahashi method: 1 numero o 1 palabra por slide\n- Signal-to-noise: eliminar todo lo que no amplifica el mensaje\n- Rehearsal: si necesitas leer la slide, tiene demasiado texto", "Formato: outline slide-by-slide + notas del speaker.\nTono: minimalista, de alto impacto.\nAudiencia: {{AUDIENCIA}}.\nAccion: disenar las slides.", ["Ninguna slide tiene mas de 10 palabras", "Cada slide tiene 1 sola idea", "Las notas del speaker estan completas", "Las transiciones son corte seco"], [{'name': 'TEMA', 'desc': 'Tema de la presentacion'}, {'name': 'AUDIENCIA', 'desc': 'Audiencia'}, {'name': 'DURACION', 'desc': 'Duracion en minutos'}])

    qspec("visual_html_autocontenido_dashboard", "Para generar un dashboard HTML autocontenido que funcione offline, sin dependencias externas. Abre en cualquier browser, imprimible, compartible por email.", "Full-Stack Data Visualizer con experiencia en dashboards HTML self-contained para reportes ejecutivos y presentaciones offline.", """HTML Dashboard:\n1. KPIs principales: numeros grandes arriba\n2. Graficos: bars, lines, pies (usando CSS puro o SVG inline)\n3. Tablas de datos: responsivas, escaneables\n4. Insights: 3-5 bullet points con lo que importa\n5. Responsive: funciona en desktop, tablet, mobile\n6. Specs: fonts inline, CSS inline, zero external dependencies""", "Metodo:\n- Self-contained: todo inline (CSS, fonts base64, SVG)\n- KPI hierarchy: lo mas importante arriba y grande\n- Progressive disclosure: resumen > detalle > datos crudos\n- Print-friendly: @media print stylesheet incluido", "Formato: especificacion HTML completa o codigo listo.\nTono: tecnico.\nAudiencia: desarrollador o creador que genera el HTML.\nAccion: generar el dashboard.", ["Zero dependencias externas", "Responsive (desktop + mobile)", "KPIs visibles sin scroll", "Print-friendly"], [{'name': 'DATOS', 'desc': 'Datos a visualizar en el dashboard'}, {'name': 'AUDIENCIA', 'desc': 'Quien vera el dashboard'}, {'name': 'MARCA', 'desc': 'Colores y fonts de marca', 'opt': True}])

    qspec("visual_before_after_transformacion", "Para crear comparaciones visuales antes/despues que demuestren impacto de forma innegable. El before/after es la prueba visual mas poderosa.", "Visual Storyteller con experiencia en case studies visuales y demostraciones de impacto para ventas y marketing.", """Before/After Visual:\n1. Seleccionar la metrica o aspecto a comparar\n2. Before: capturar el estado anterior con datos/visual concreto\n3. After: mostrar el estado actual con los mismos parametros\n4. Delta: cuantificar la diferencia (%, absoluto, x veces)\n5. Formato: lado a lado o timeline\n6. Caption: 1 oracion que cuente la historia del cambio""", "Metodo:\n- Same parameters: comparar manzanas con manzanas\n- Quantify the delta: numeros > adjetivos\n- Let the visual speak: minimal text, maximal contrast\n- Honest comparison: no cherry-pick el mejor after vs peor before", "Formato: spec de before/after con datos y layout.\nTono: factual, visual.\nAudiencia: stakeholders o prospectos.\nAccion: usar en la proxima presentacion de resultados.", ["Los parametros de comparacion son identicos", "El delta esta cuantificado", "La comparacion es honesta", "La caption cuenta la historia en 1 oracion"], [{'name': 'METRICA', 'desc': 'Que estas comparando'}, {'name': 'BEFORE', 'desc': 'Datos o estado anterior'}, {'name': 'AFTER', 'desc': 'Datos o estado actual'}])

    qspec("visual_mapa_mental_concepto", "Para crear un mapa mental que descomponga un concepto complejo en partes navegables. El mapa mental es el GPS del pensamiento — muestra la estructura que la mente no puede sostener sola.", "Knowledge Architect con experiencia en visualizacion de conocimiento y mapas mentales para planificacion estrategica y educacion.", """Mapa mental:\n1. Nodo central: concepto principal en 3 palabras max\n2. Ramas nivel 1: 5-7 dimensiones principales (MECE)\n3. Ramas nivel 2: sub-temas por dimension\n4. Relaciones cruzadas: conexiones entre ramas\n5. Color coding: una familia de color por rama\n6. Formato: texto estructurado para Mermaid mindmap o XMind""", "Metodo:\n- Central > branches > leaves: de lo general a lo especifico\n- MECE branches: mutuamente excluyentes, colectivamente exhaustivas\n- Cross-links: las conexiones entre ramas revelan insights\n- Limit depth: max 3 niveles para mantener legibilidad", "Formato: mapa mental en texto estructurado o Mermaid.\nTono: visual-analitico.\nAudiencia: quien necesita entender la estructura del concepto.\nAccion: usar como guia de navegacion del tema.", ["El nodo central cabe en 3 palabras", "Las ramas nivel 1 son MECE", "Las relaciones cruzadas estan identificadas", "Max 3 niveles de profundidad"], [{'name': 'CONCEPTO', 'desc': 'Concepto a mapear'}, {'name': 'PROPOSITO', 'desc': 'Para que necesitas el mapa (estudiar, planificar, comunicar)'}])

    qspec("visual_icon_system_coherente", "Para disenar un sistema de iconos coherente para una interfaz, presentacion o documento. Los iconos son el micro-lenguaje visual — inconsistencia aqui grita amateur.", "UI/Icon Designer con experiencia en sistemas de iconografia para productos digitales y documentacion corporativa.", """Sistema de iconos:\n1. Estilo: outlined, filled, duotone (elegir 1, mantener consistencia)\n2. Grid: tamano base (24px, 32px), stroke width, corner radius\n3. Catalogo: icono por concepto clave del proyecto (min 20)\n4. Naming convention: nombre descriptivo en ingles\n5. Fuente: libreria recomendada (Lucide, Phosphor, Heroicons, custom)\n6. Uso: guia de cuando usar cual icono""", "Metodo:\n- Consistency > creativity: 1 estilo, sin mezclar\n- Semantic clarity: el icono debe entenderse sin label\n- Grid-based: todos los iconos en la misma grid\n- Test: 5-second recognition test con usuarios", "Formato: catalogo de iconos + guia de estilo + fuente.\nTono: tecnico-visual.\nAudiencia: disenador o developer.\nAccion: implementar el sistema de iconos.", ["Todos los iconos son del mismo estilo", "La grid es consistente", "El catalogo cubre los conceptos clave", "La naming convention es clara"], [{'name': 'PROYECTO', 'desc': 'Proyecto o producto'}, {'name': 'ESTILO', 'desc': 'Estilo preferido (outlined, filled, duotone)', 'opt': True}])

    # ─── AGENTES GAPS (+16) ───

    qspec("agentes_gemini_gem_especializado", "Para crear un Gemini Gem que funcione como asistente especializado con personalidad y scope definidos.", "Disenador de Gems con experiencia en configuracion de asistentes Gemini para productividad empresarial.", """Gemini Gem:\n1. Nombre y personalidad del Gem\n2. Instrucciones de sistema con scope y boundaries\n3. Knowledge sources: que documentos o URLs alimentan al Gem\n4. Formato default de respuesta\n5. 5 examples de interaccion ideal\n6. Testing plan: 10 queries de prueba""", "Metodo:\n- Scope-first: que hace y que NO hace\n- Knowledge-grounded: respuestas basadas en sources, no en alucinacion\n- Personality calibration: tono y estilo consistentes\n- Test before publish", "Formato: instrucciones completas del Gem + examples + test plan.\nTono: tecnico.\nAudiencia: creador del Gem.\nAccion: crear el Gem en Gemini.", ["Las instrucciones tienen scope y boundaries", "Los knowledge sources estan definidos", "Los 5 examples son representativos", "El test plan cubre edge cases"], [{'name': 'FUNCION', 'desc': 'Funcion principal del Gem'}, {'name': 'AUDIENCIA', 'desc': 'Quien usara el Gem'}, {'name': 'SOURCES', 'desc': 'Documentos o URLs para alimentar el Gem', 'opt': True}])

    qspec("agentes_notebooklm_cuaderno", "Para configurar un cuaderno de NotebookLM que funcione como base de conocimiento consultable y generador de contenido multimedia.", "Producer de NotebookLM con experiencia en curaduria de cuadernos para investigacion, educacion y produccion de contenido.", """Cuaderno NLM:\n1. Objetivo del cuaderno: que preguntas debe poder responder\n2. Fuentes: seleccion y curaduria (max 50, calidad > cantidad)\n3. Organizacion: naming convention de sources\n4. Prompt de chat: como configurar la conversacion\n5. Outputs multimedia: audio overview, slides, infografia\n6. Mantenimiento: cuando agregar/remover sources""", "Metodo:\n- Curate > dump: seleccionar fuentes con intencion\n- Source quality: la calidad del output = calidad de los inputs\n- Structured queries: preguntas especificas producen mejores respuestas\n- Multimedia pipeline: sources > chat > audio/slides/infographic", "Formato: plan de cuaderno + lista de sources + prompts de chat.\nTono: practico.\nAudiencia: profesional que usa NLM.\nAccion: crear el cuaderno con las primeras 10 sources.", ["Las fuentes estan curadas (no dumped)", "El objetivo del cuaderno es especifico", "Los prompts de chat son efectivos", "El plan de mantenimiento esta definido"], [{'name': 'TEMA', 'desc': 'Tema del cuaderno'}, {'name': 'FUENTES', 'desc': 'Tipo de fuentes disponibles'}, {'name': 'OUTPUTS', 'desc': 'Que tipo de outputs necesitas (audio, slides, texto)'}])

    qspec("agentes_text_expander_biblioteca", "Para configurar un text expander (Espanso, TextExpander, Alfred) con tu biblioteca de prompts para acceso instantaneo.", "Productivity Engineer con experiencia en configuracion de text expanders para workflows de alto rendimiento con IA.", """Text Expander Setup:\n1. Herramienta seleccionada: Espanso (free) vs TextExpander vs Alfred\n2. Naming convention: prefijo + categoria + accion (ej: ;prod-ritual)\n3. Top 20 prompts a configurar primero (los que mas usas)\n4. Variables fill-in: {{campos}} que el usuario completa al expandir\n5. Organizacion: carpetas/grupos por categoria\n6. Sync: como sincronizar entre dispositivos""", "Metodo:\n- Start with 20: los mas usados primero, no los 365\n- Consistent triggers: ;categoria-accion (facil de recordar)\n- Fill-in fields: para parametros que cambian por uso\n- Monthly review: agregar, mejorar, eliminar snippets", "Formato: guia de setup + 20 snippets configurados + naming convention.\nTono: tecnico paso a paso.\nAudiencia: profesional que quiere acceso instantaneo a prompts.\nAccion: instalar y configurar los primeros 10 snippets hoy.", ["La naming convention es consistente y memorable", "Los 20 snippets son los de mayor frecuencia de uso", "Los fill-in fields cubren los parametros variables", "La guia de sync esta incluida"], [{'name': 'HERRAMIENTA', 'desc': 'Text expander elegido (Espanso, TextExpander, Alfred)'}, {'name': 'DISPOSITIVOS', 'desc': 'Dispositivos a sincronizar'}])

    qspec("agentes_priming_contexto_sesion", "Para crear un prompt de priming que configure al asistente con tu contexto profesional al inicio de cada sesion. El priming ahorra 10 minutos de contexto cada vez.", "Prompt Architect con experiencia en diseno de system prompts y session priming para profesionales que usan IA diariamente.", """Prompt de Priming:\n1. Quien eres: rol, empresa, sector, experiencia\n2. Como trabajas: herramientas, preferencias, restricciones\n3. Tono preferido: como quieres que te hable la IA\n4. Formato default: como prefieres recibir outputs\n5. Reglas: que debe hacer siempre / que nunca\n6. Contexto actual: proyecto o foco de este periodo""", "Metodo:\n- Max 200 palabras: denso, no verbose\n- Update quarterly: el contexto cambia\n- Test: el priming debe producir primera respuesta calibrada sin correccion\n- Portable: funciona en ChatGPT, Claude, Gemini", "Formato: prompt de priming listo para copiar (max 200 palabras).\nTono: profesional.\nAudiencia: tu yo futuro que inicia una sesion nueva.\nAccion: pegar al inicio de cada sesion nueva.", ["Cabe en 200 palabras", "Cubre rol, tono, formato y reglas", "Funciona cross-platform", "No requiere edicion para uso diario"], [{'name': 'ROL', 'desc': 'Tu rol profesional'}, {'name': 'SECTOR', 'desc': 'Tu sector o industria'}, {'name': 'PREFERENCIAS', 'desc': 'Como prefieres que la IA te responda'}])

    qspec("agentes_workflow_multimodelo", "Para disenar un workflow que use el modelo correcto para cada tarea: GPT para creatividad, Claude para analisis, Gemini para research, Perplexity para busqueda.", "AI Workflow Architect con experiencia en orquestacion multi-modelo y seleccion de LLMs para tareas especificas.", """Workflow multi-modelo:\n1. Inventario de tareas por tipo (creacion, analisis, busqueda, codigo, visual)\n2. Fortaleza por modelo: GPT, Claude, Gemini, Perplexity, Copilot\n3. Asignacion: modelo optimo por tipo de tarea\n4. Handoff: como pasar output de un modelo a otro\n5. Cost optimization: cuando usar modelo caro vs barato\n6. Workflow diagramado: que modelo en que momento""", "Metodo:\n- Right model for right job: no usar GPT-4 para todo\n- Specialized > general: cada modelo tiene fortalezas\n- Cost-aware: usar modelos baratos para tareas simples\n- Pipeline: output de uno = input del siguiente", "Formato: workflow diagramado + tabla modelo/tarea + guia de handoff.\nTono: tecnico-estrategico.\nAudiencia: profesional que usa multiples IAs.\nAccion: implementar el workflow esta semana.", ["La asignacion modelo-tarea esta justificada", "Los handoffs entre modelos estan definidos", "La optimizacion de costos esta considerada", "El workflow es ejecutable con herramientas actuales"], [{'name': 'TAREAS', 'desc': 'Tipos de tareas que haces con IA'}, {'name': 'MODELOS', 'desc': 'Modelos/herramientas IA que tienes acceso'}, {'name': 'PRESUPUESTO', 'desc': 'Presupuesto mensual en IA', 'opt': True}])

    qspec("agentes_quality_rubric_outputs", "Para crear una rubrica de calidad para evaluar outputs de IA de forma consistente y objetiva. Sin rubrica, 'esta bueno' es opinion; con rubrica, es medicion.", "QA Specialist de Contenido con experiencia en diseno de rubricas de evaluacion para outputs de LLMs y contenido editorial.", """Rubrica de calidad:\n1. Dimensiones de calidad: precision, completitud, claridad, formato, tono, accionabilidad\n2. Escala por dimension: 1-10 con descriptores por nivel\n3. Peso por dimension: no todas pesan igual\n4. Score minimo aceptable: umbral de aprobacion\n5. Ejemplo de output 10/10 vs 5/10 vs 2/10\n6. Protocolo de evaluacion: como aplicar la rubrica en <2 min""", "Metodo:\n- Measurable criteria: cada dimension con descriptores claros\n- Weighted scoring: precision pesa mas que formato\n- Calibration: evaluar 3 outputs con la rubrica para calibrar\n- Speed: si toma mas de 2 min evaluar, la rubrica es muy compleja", "Formato: rubrica completa + ejemplos por nivel + protocolo.\nTono: tecnico.\nAudiencia: profesional que evalua outputs de IA regularmente.\nAccion: evaluar los proximos 5 outputs con esta rubrica.", ["Las dimensiones son medibles (no subjetivas)", "Los descriptores por nivel son claros", "Los pesos estan justificados", "El protocolo de evaluacion cabe en 2 minutos"], [{'name': 'TIPO_OUTPUT', 'desc': 'Tipo de output a evaluar (texto, analisis, presentacion, etc.)'}, {'name': 'ESTANDAR', 'desc': 'Nivel de calidad requerido (profesional, ejecutivo, publicacion)'}])

    # ─── STACK (M9) — 15 prompts ───

    qspec("stack_auditar_herramientas_personal", "Para auditar tu stack de herramientas y eliminar redundancias. El profesional promedio paga por 8 herramientas y usa 3. Las otras 5 son desperdicio.", "Consultor de Productividad Digital con experiencia en stack optimization para equipos remotos y profesionales independientes.", """Stack Audit:\n1. Inventario completo: herramienta, costo, frecuencia de uso, valor aportado\n2. Clasificacion: esencial / util / redundante / abandonada\n3. Mapa de solapamientos: que herramientas hacen lo mismo\n4. Stack optimo: consolidar a las minimas necesarias\n5. Migration plan: como migrar de las eliminadas\n6. Ahorro estimado: dinero + horas de gestion""", "Metodo:\n- Inventory first: no puedes optimizar lo que no conoces\n- Usage audit: frecuencia real, no percibida\n- Consolidation: 1 herramienta buena > 3 mediocres\n- Total cost: licencia + tiempo de aprendizaje + mantenimiento", "Formato: inventario + mapa de solapamiento + stack optimo + ahorro.\nTono: analitico.\nAudiencia: profesional o equipo.\nAccion: cancelar la primera herramienta redundante.", ["Todas las herramientas estan inventariadas con costo", "Los solapamientos estan identificados", "El stack optimo es min. 30% mas pequeno", "El ahorro esta cuantificado"], [{'name': 'HERRAMIENTAS', 'desc': 'Lista de herramientas que usas'}, {'name': 'PRESUPUESTO', 'desc': 'Gasto mensual actual en herramientas', 'opt': True}])

    qspec("stack_seleccionar_herramienta", "Para evaluar y seleccionar la herramienta correcta cuando tienes multiples opciones. La decision de herramienta no es tecnica — es estrategica.", "Technology Evaluator con experiencia en seleccion de herramientas para equipos y organizaciones.", """Evaluacion de herramienta:\n1. Requisitos: must-have vs nice-to-have (no mas de 10)\n2. Candidatas: 3-5 opciones a evaluar\n3. Criterios: funcionalidad, precio, UX, integraciones, soporte, escalabilidad\n4. Scoring: tabla comparativa (1-5 por criterio ponderado)\n5. Trial plan: como probar la top 2 antes de decidir\n6. Decision + justificacion""", "Metodo:\n- Requirements-first: saber que necesitas antes de comparar\n- Weighted scoring: no todos los criterios pesan igual\n- Trial > demo: usar la herramienta, no solo verla\n- Total cost: no solo precio, sino costo de cambio y aprendizaje", "Formato: tabla comparativa + scoring + recomendacion.\nTono: analitico-pragmatico.\nAudiencia: decision-maker.\nAccion: iniciar trial de la herramienta ganadora.", ["Los requisitos son especificos (no genericos)", "La tabla tiene scoring ponderado", "El trial plan es ejecutable en 1 semana", "La decision incluye justificacion y riesgos"], [{'name': 'NECESIDAD', 'desc': 'Que problema resuelve la herramienta'}, {'name': 'CANDIDATAS', 'desc': 'Herramientas a comparar'}, {'name': 'PRESUPUESTO', 'desc': 'Presupuesto disponible', 'opt': True}])

    qspec("stack_integraciones_mapa", "Para mapear como se conectan tus herramientas entre si e identificar gaps de integracion que causan trabajo manual innecesario.", "Integration Architect con experiencia en diseno de ecosistemas de herramientas conectadas para equipos de operaciones.", """Mapa de integraciones:\n1. Diagrama: como fluyen los datos entre herramientas\n2. Integraciones activas: que esta conectado y como\n3. Gaps: donde hay transferencia manual (copiar/pegar entre apps)\n4. Oportunidades: integraciones nativas disponibles pero no configuradas\n5. Automatizaciones posibles: con Zapier, Make, n8n\n6. Plan de implementacion: priorizado por horas ahorradas""", "Metodo:\n- Data flow mapping: de donde sale el dato, a donde llega\n- Gap = manual transfer: cada copiar/pegar es un gap\n- Native > third-party: preferir integraciones nativas\n- ROI per integration: horas ahorradas / horas de setup", "Formato: diagrama de integraciones + gaps + plan.\nTono: tecnico-practico.\nAudiencia: equipo de operaciones o profesional.\nAccion: configurar la integracion de mayor ROI.", ["El diagrama cubre todas las herramientas principales", "Los gaps de transferencia manual estan identificados", "Las oportunidades de integracion son concretas", "El plan esta priorizado por ROI"], [{'name': 'HERRAMIENTAS', 'desc': 'Herramientas en tu stack'}, {'name': 'FLUJOS', 'desc': 'Flujos de trabajo principales'}])

    # ─── AUTOMATIZACION (M10) — 17 prompts adicionales ───

    qspec("automatizacion_ritual_productivo_semiautomatico", "Para convertir un ritual productivo manual en un flujo semi-automatizado que reduzca fricciones y asegure consistencia.", "Disenador de Rituales Automatizados con experiencia en behavioural design y automatizacion personal.", """Ritual semi-automatizado:\n1. Mapear el ritual actual: pasos, tiempos, puntos de friccion\n2. Clasificar: automatizable vs humano necesario\n3. Disenar triggers automaticos para cada paso\n4. Crear fallbacks para cuando la automatizacion falle\n5. Medir: mejora en consistencia y tiempo""", "Metodo:\n- Friction-first: automatizar los puntos de mayor friccion\n- Human-in-the-loop: el humano decide, la maquina ejecuta\n- Graceful degradation: si falla la automatizacion, el ritual sigue\n- Measure: antes vs despues en tiempo y consistencia", "Formato: mapa del ritual + automatizaciones + metricas.\nTono: practico.\nAudiencia: profesional que tiene rituales productivos.\nAccion: automatizar el punto de mayor friccion.", ["El ritual actual esta mapeado con tiempos", "Los puntos automatizables estan justificados", "Los fallbacks estan disenados", "La mejora esta cuantificada"], [{'name': 'RITUAL', 'desc': 'Ritual o rutina a automatizar'}, {'name': 'FRICCIONES', 'desc': 'Puntos de mayor friccion'}])

    qspec("automatizacion_zapier_make_receta", "Para disenar una receta de automatizacion en Zapier o Make con triggers, acciones, filtros y manejo de errores.", "Automation Specialist con experiencia en Zapier y Make para procesos de marketing, ventas y operaciones.", """Receta de automatizacion:\n1. Trigger: que evento inicia el flujo\n2. Filtros: condiciones para continuar o detenerse\n3. Acciones: pasos secuenciales del flujo\n4. Transformaciones de datos entre pasos\n5. Error handling: que pasa si falla\n6. Testing: como probar antes de activar en produccion""", "Metodo:\n- Trigger > Filter > Action: la estructura basica\n- Test with real data: no solo con datos de prueba\n- Error notification: siempre saber cuando algo falla\n- Start simple: 3 pasos max, luego iterar", "Formato: receta paso a paso lista para implementar.\nTono: tecnico paso a paso.\nAudiencia: profesional configurando su primera automatizacion.\nAccion: crear la automatizacion hoy.", ["El trigger esta correctamente definido", "Los filtros previenen ejecuciones innecesarias", "El error handling esta configurado", "El testing plan esta incluido"], [{'name': 'PROCESO', 'desc': 'Proceso a automatizar'}, {'name': 'PLATAFORMA', 'desc': 'Zapier o Make'}, {'name': 'APPS', 'desc': 'Apps involucradas en el flujo'}])

    # ─── ENGINE (M11) — 15 prompts ───

    qspec("engine_asistente_corporativo_privado", "Para disenar un asistente corporativo privado alimentado con el conocimiento de tu organizacion. Tu propio ChatGPT, entrenado con TU informacion.", "Arquitecto de AI Corporativa con experiencia en despliegue de asistentes privados con RAG para empresas de 50-5000 empleados.", """Asistente corporativo:\n1. Scope: que preguntas debe poder responder\n2. Knowledge base: documentos, wikis, procesos a ingestar\n3. Acceso: quien puede usarlo, roles, permisos\n4. Personalidad: tono, formato, reglas de interaccion\n5. Seguridad: que NO puede decir o compartir\n6. Metricas de adopcion: como medir uso y satisfaccion""", "Metodo:\n- RAG architecture: retrieval augmented generation\n- Security-first: el asistente no puede filtrar info confidencial\n- User adoption: si no lo usan, no sirve\n- Iterative improvement: mejorar con feedback real", "Formato: spec del asistente + KB plan + seguridad + metricas.\nTono: tecnico-estrategico.\nAudiencia: equipo de IT o innovacion.\nAccion: definir el scope y empezar la curaduria de KB.", ["El scope es claro y acotado", "La seguridad esta disenada (no como afterthought)", "El plan de adopcion existe", "Las metricas son medibles"], [{'name': 'ORGANIZACION', 'desc': 'Tipo y tamano de organizacion'}, {'name': 'SCOPE', 'desc': 'Que debe poder responder el asistente'}, {'name': 'FUENTES', 'desc': 'Fuentes de conocimiento disponibles'}])

    qspec("engine_chatbot_ventas_calificacion", "Para crear un chatbot que califique leads automaticamente antes de pasarlos a ventas. El chatbot hace las preguntas correctas para que ventas solo hable con prospectos calificados.", "Sales Operations Architect con experiencia en chatbots de calificacion para pipelines B2B de alto volumen.", """Chatbot de calificacion:\n1. Preguntas de calificacion: BANT (Budget, Authority, Need, Timeline)\n2. Flujo conversacional: arbol de decisiones con respuestas\n3. Scoring: puntuacion automatica por respuesta\n4. Handoff: criterios para pasar a ventas vs seguir en nurturing\n5. CRM integration: como se registra la informacion\n6. Personalidad: tono, estilo, velocidad de respuesta""", "Metodo:\n- BANT framework: Budget, Authority, Need, Timeline\n- Progressive qualification: no todas las preguntas al inicio\n- Conversational > form: el chatbot debe sentirse como conversacion\n- Threshold scoring: solo leads con score > X pasan a ventas", "Formato: flujo conversacional + scoring + handoff rules.\nTono: tecnico-comercial.\nAudiencia: equipo de ventas/marketing.\nAccion: implementar el chatbot.", ["Las preguntas cubren BANT", "El scoring es automatico y transparente", "Los criterios de handoff son claros", "El flujo es conversacional (no un formulario disfrazado)"], [{'name': 'PRODUCTO', 'desc': 'Producto o servicio que vendes'}, {'name': 'ICP', 'desc': 'Perfil del cliente ideal'}, {'name': 'CRM', 'desc': 'CRM actual', 'opt': True}])

    # ─── PRESENTACION + COMUNICACION (M13) — 27 prompts ───

    qspec("presentacion_deck_inversores", "Para crear un pitch deck que convenza inversores. El deck no es un resumen del negocio — es una narrativa de oportunidad con evidencia.", "Startup Advisor con experiencia en pitch decks exitosos para rondas de inversion Serie A-C en LatAm y USA.", """Pitch Deck para inversores:\n1. Problem: dolor real, cuantificado, no teorico\n2. Solution: tu solucion en 1 oracion\n3. Market: TAM/SAM/SOM con fuentes\n4. Product: demo o screenshots\n5. Traction: metricas de crecimiento\n6. Business model: como ganas dinero\n7. Team: por que ESTE equipo\n8. Ask: cuanto levantas y para que\n9. Max 12 slides""", "Metodo:\n- Sequoia format: problem > solution > market > product > traction > team > ask\n- Show don't tell: graficos > texto\n- Traction is king: numeros hablan mas fuerte que promesas\n- 12 slides max: respeta el tiempo del inversor", "Formato: 12 slides con contenido + notas del speaker.\nTono: confiado, basado en datos.\nAudiencia: inversores.\nAccion: presentar en la proxima reunion.", ["El problem es cuantificado (no anecdotico)", "El market size tiene fuentes", "La traction tiene numeros reales", "El ask es claro (monto + uso)"], [{'name': 'STARTUP', 'desc': 'Tu startup o proyecto'}, {'name': 'RONDA', 'desc': 'Tipo de ronda (seed, Series A, etc.)'}, {'name': 'METRICAS', 'desc': 'Metricas de traction actuales'}])

    qspec("comunicacion_escalacion_profesional", "Para escalar un problema de forma que genere accion sin generar friccion. La escalacion profesional preserva relaciones mientras resuelve bloqueos.", "Consultor de Comunicacion Organizacional con experiencia en escalaciones en entornos corporativos de alta presion.", """Email de escalacion:\n1. Subject: [ESCALACION] + tema en 7 palabras\n2. TL;DR: que necesitas y para cuando (2 lineas)\n3. Contexto: que se intento y por que no funciono\n4. Impacto: que pasa si no se resuelve (cuantificado)\n5. Opciones: 2-3 alternativas para resolver\n6. Ask: decision o accion requerida del destinatario""", "Metodo:\n- Facts > emotions: escalar con datos, no con frustracion\n- Options > complaints: siempre ofrecer soluciones\n- Impact quantification: el costo de no actuar\n- Respect the chain: escalar al nivel correcto, no saltar niveles", "Formato: email listo para enviar.\nTono: profesional, firme sin ser agresivo.\nAudiencia: decision-maker que puede desbloquear.\nAccion: enviar y obtener respuesta en 24h.", ["El TL;DR cabe en 2 lineas", "El impacto esta cuantificado", "Ofrece opciones (no solo queja)", "El tono preserva la relacion"], [{'name': 'PROBLEMA', 'desc': 'Que necesitas escalar'}, {'name': 'DESTINATARIO', 'desc': 'A quien va dirigida la escalacion'}, {'name': 'IMPACTO', 'desc': 'Impacto si no se resuelve'}])

    qspec("comunicacion_feedback_positivo_refuerzo", "Para dar feedback positivo que refuerce comportamientos deseados con la misma estructura que el feedback constructivo. El reconocimiento estructurado es 3x mas efectivo que el generico.", "Coach de Desarrollo de Equipos con experiencia en positive reinforcement y cultura de reconocimiento en organizaciones de alto rendimiento.", """Feedback positivo SBI:\n1. Situacion: cuando/donde ocurrio\n2. Comportamiento: que hizo exactamente (observable)\n3. Impacto: que efecto positivo tuvo (cuantificado si es posible)\n4. Refuerzo: por que quieres que siga haciendolo\n5. Conexion: como conecta con los valores del equipo/organizacion""", "Metodo:\n- SBI (Situation-Behavior-Impact): igual que el constructivo\n- Specific > generic: 'buen trabajo' no sirve; 'la forma en que...' si\n- Timely: dar el feedback lo antes posible\n- Public when appropriate: el reconocimiento publico multiplica el efecto", "Formato: script de feedback listo para dar.\nTono: genuino, especifico.\nAudiencia: la persona que hizo algo bien.\nAccion: dar el feedback hoy.", ["La situacion es especifica (no vaga)", "El comportamiento es observable (no interpretacion)", "El impacto esta cuantificado o es concreto", "El refuerzo conecta con valores"], [{'name': 'PERSONA', 'desc': 'Persona a reconocer'}, {'name': 'COMPORTAMIENTO', 'desc': 'Que hizo bien (hechos observables)'}, {'name': 'IMPACTO', 'desc': 'Que impacto positivo tuvo'}])

    # ─── CROSS-CUTTING: DECISION ───

    qspec("decision_framework_rapido_5min", "Para tomar decisiones reversibles en 5 minutos sin paralisis de analisis. El 80% de las decisiones profesionales no necesitan mas de 5 minutos de analisis.", "Decision Coach con experiencia en frameworks de decision rapida para ejecutivos y emprendedores.", """Decision en 5 minutos:\n1. Reversible o irreversible? Si reversible: decide rapido.\n2. Que es lo peor que puede pasar? Es tolerable?\n3. Tengo el 70% de la informacion? Si: decide.\n4. Cual es el costo de NO decidir hoy?\n5. Decision + 1 razon + proxima accion""", "Metodo:\n- Bezos Type 2: si es reversible, no pierdas tiempo\n- 70% rule: decide con 70% de info, el 100% nunca llega\n- Regret minimization: que decisión lamentaré más NO haber tomado?\n- Document: registrar la decision y su razonamiento", "Formato: decision en 1 linea + razonamiento + accion.\nTono: directo, sin rodeos.\nAudiencia: decision-maker paralizado.\nAccion: decidir AHORA.", ["La decision esta clasificada (reversible/irreversible)", "El peor escenario es tolerable", "La decision tiene razonamiento documentado", "La proxima accion es inmediata"], [{'name': 'DECISION', 'desc': 'Decision pendiente'}, {'name': 'CONTEXTO', 'desc': 'Contexto relevante'}])

    qspec("decision_matriz_ponderada", "Para tomar decisiones complejas con multiples criterios de forma objetiva y transparente. La matriz ponderada reemplaza intuicion con estructura.", "Analista de Decisiones con experiencia en MCDA (Multi-Criteria Decision Analysis) para inversiones y estrategia.", """Matriz de decision ponderada:\n1. Opciones: 3-5 alternativas a comparar\n2. Criterios: 5-8 factores de evaluacion\n3. Pesos: importancia relativa de cada criterio (total = 100%)\n4. Scoring: evaluar cada opcion por criterio (1-5)\n5. Score ponderado: score × peso por celda\n6. Ranking: total ponderado por opcion\n7. Sensitivity: que pasa si cambio los pesos""", "Metodo:\n- MCDA: Multi-Criteria Decision Analysis\n- Separate weighting from scoring: primero pesos, despues scores\n- Sensitivity analysis: la decision es robusta o depende de 1 peso?\n- Document: la transparencia de la decision es tan valiosa como la decision misma", "Formato: tabla de decision + sensitivity + recomendacion.\nTono: analitico.\nAudiencia: equipo de decision.\nAccion: tomar la decision basada en el ranking.", ["Los criterios son relevantes y no redundantes", "Los pesos suman 100%", "El scoring es consistente entre opciones", "El sensitivity analysis muestra robustez"], [{'name': 'OPCIONES', 'desc': 'Alternativas a comparar'}, {'name': 'CRITERIOS', 'desc': 'Factores de evaluacion'}])

    # ─── CROSS-CUTTING: LIDERAZGO ───

    qspec("liderazgo_conversacion_dificil", "Para preparar una conversacion dificil que preserve la relacion y logre el resultado. Las conversaciones que evitas son las que mas necesitas tener.", "Coach de Comunicacion Dificil con experiencia en Crucial Conversations y mediacion de conflictos en entornos corporativos.", """Preparacion para conversacion dificil:\n1. Objetivo: que quiero que pase como resultado\n2. Hechos: datos observables (no interpretaciones)\n3. Impacto: como me afecta a mi y al equipo\n4. Apertura: frase de inicio que no ponga a la defensiva\n5. Escucha: preguntas para entender su perspectiva\n6. Acuerdo: propuesta de camino a seguir\n7. Ensayo: practicar la apertura 3 veces""", "Metodo:\n- Crucial Conversations: start with heart, learn to look, make it safe\n- Facts first: hechos observables, no juicios\n- And stance: mi perspectiva AND tu perspectiva (no or)\n- Desired outcome: empezar con el fin en mente", "Formato: guia de preparacion + script de apertura + preguntas de escucha.\nTono: firme, empatico.\nAudiencia: lider que enfrenta la conversacion.\nAccion: tener la conversacion esta semana.", ["El objetivo esta claro antes de hablar", "Los hechos son observables (no interpretaciones)", "La apertura no pone a la defensiva", "El camino a seguir es concreto"], [{'name': 'SITUACION', 'desc': 'Situacion que requiere la conversacion'}, {'name': 'PERSONA', 'desc': 'Con quien es la conversacion'}, {'name': 'OBJETIVO', 'desc': 'Que resultado quieres'}])

    qspec("liderazgo_one_on_one_efectivo", "Para conducir one-on-ones que desarrollen personas, no solo revisen tareas. El 1:1 es la herramienta de liderazgo mas poderosa y mas desperdiciada.", "Leadership Coach con experiencia en coaching de managers para empresas de tecnologia en hipercrecimiento.", """One-on-One efectivo:\n1. Agenda del reportee: el 70% lo define el, no tu\n2. Check-in: como estas? (genuino, no protocolar)\n3. Progreso: que has logrado? que te bloquea?\n4. Desarrollo: que estas aprendiendo? que necesitas?\n5. Feedback bidireccional: que puedo hacer mejor como lider?\n6. Cierre: 1 accion concreta cada uno\n7. Frecuencia: semanal 30 min > mensual 2 horas""", "Metodo:\n- Their agenda: el 1:1 es PARA ellos, no para ti\n- Ask > tell: preguntar mas que instruir\n- Career conversations: hablar de desarrollo, no solo de tareas\n- Follow through: lo que se compromete se cumple", "Formato: template de 1:1 + preguntas + cadencia.\nTono: humano, coaching.\nAudiencia: manager que lidera personas.\nAccion: reprogramar el proximo 1:1 con este formato.", ["La agenda es 70% del reportee", "Hay espacio para feedback bidireccional", "Hay conversacion de desarrollo (no solo tareas)", "Cada 1:1 cierra con 1 accion por persona"], [{'name': 'EQUIPO', 'desc': 'Tamano y perfil de tu equipo'}, {'name': 'FRECUENCIA', 'desc': 'Frecuencia actual de 1:1s'}])

    # ─── CROSS-CUTTING: APRENDIZAJE ───

    qspec("aprendizaje_feynman_explicar", "Para dominar un concepto explicandolo con simplicidad. Si no puedes explicarlo simple, no lo entiendes. La Tecnica Feynman convierte confusion en dominio.", "Educador y Simplificador de Conocimiento con la filosofia de Richard Feynman: la complejidad es falta de comprension.", """Tecnica Feynman:\n1. Explica el concepto como si fuera para alguien de 12 anos\n2. Identifica donde la explicacion falla (gap de comprension)\n3. Vuelve a la fuente para llenar el gap\n4. Crea una analogia que ancle el entendimiento\n5. Entrega 3 niveles: simple (12 anos), intermedio (colega), profundo (experto)\n6. Mapa de conceptos relacionados""", "Metodo:\n- Feynman Technique: explain > identify gaps > relearn > simplify\n- Analogy is king: anclar lo abstracto en lo concreto\n- If you can't explain it simply: you don't understand it\n- 3 levels: asegura que puedes adaptar a cualquier audiencia", "Formato: explicacion en 3 niveles + analogias + mapa de conceptos.\nTono: pedagogico, claro.\nAudiencia: tu mismo (para aprender) o tu audiencia (para ensenar).\nAccion: explicar el concepto a alguien hoy.", ["La explicacion simple funciona para alguien de 12 anos", "Los gaps de comprension estan identificados", "Las analogias son memorables y precisas", "Los 3 niveles cubren simple a profundo"], [{'name': 'CONCEPTO', 'desc': 'Concepto a dominar'}, {'name': 'NIVEL_ACTUAL', 'desc': 'Tu nivel actual de comprension'}])

    qspec("aprendizaje_plan_90_dias_competencia", "Para adquirir una nueva competencia profesional en 90 dias con plan estructurado. 90 dias es el tiempo minimo para pasar de novato a operativo.", "Learning Designer con experiencia en diseno de programas de upskilling acelerado para profesionales.", """Plan de 90 dias:\n1. Competencia target y nivel objetivo (novato > operativo)\n2. Recursos curados: top 3 libros, top 5 cursos, top 3 practicantes a seguir\n3. Progresion semanal con milestones verificables\n4. Proyectos practicos: min 3 proyectos reales (no ejercicios)\n5. Accountability: como medir progreso\n6. Ajuste: review quincenal para recalibrar""", "Metodo:\n- Project-based learning: aprender haciendo, no leyendo\n- 70-20-10: 70% practica, 20% mentores, 10% teoria\n- Public learning: compartir lo que aprendes acelera la retencion\n- Milestone-driven: si no puedes demostrar progreso, recalibrar", "Formato: plan de 12 semanas + recursos + proyectos.\nTono: motivador-estructurado.\nAudiencia: profesional que quiere upskill.\nAccion: empezar semana 1 hoy.", ["Los recursos estan curados (no un dump de links)", "Los milestones son verificables", "Los proyectos son reales (no toy problems)", "El review quincenal esta calendarizado"], [{'name': 'COMPETENCIA', 'desc': 'Skill a desarrollar'}, {'name': 'NIVEL_ACTUAL', 'desc': 'Tu nivel actual'}, {'name': 'HORAS_SEMANALES', 'desc': 'Horas semanales disponibles'}])

    # ─── CROSS-CUTTING: NEGOCIACION ───

    qspec("negociacion_preparar_conversacion", "Para llegar preparado a cualquier negociacion con BATNA, ZOPA e intereses claros. La negociacion se gana en la preparacion, no en la mesa.", "Negociador Senior con formacion en Harvard Negotiation Project (Getting to Yes) y experiencia en negociaciones de alto impacto.", """Preparacion de negociacion:\n1. Mis intereses: que necesito realmente (no solo mi posicion)\n2. Sus intereses: que necesita la contraparte\n3. BATNA: mi mejor alternativa si no hay acuerdo\n4. ZOPA: zona de posible acuerdo entre ambos\n5. Concesiones: 3-5 cosas de bajo costo para mi, alto valor para ellos\n6. Apertura: estrategia de anclaje y primera oferta\n7. Respuestas a 5 tacticas comunes""", "Metodo:\n- Harvard Principled Negotiation: interests > positions\n- BATNA: tu poder en la negociacion = tu alternativa\n- ZOPA: si no existe, no hay deal posible\n- Value creation: expand the pie before dividing it", "Formato: brief de negociacion + analisis BATNA/ZOPA + estrategia.\nTono: estrategico.\nAudiencia: quien va a negociar.\nAccion: ir preparado a la proxima reunion.", ["Los intereses de ambas partes estan identificados", "El BATNA esta calculado", "Las concesiones son de bajo costo/alto valor", "Las respuestas a tacticas estan ensayadas"], [{'name': 'CONTEXTO', 'desc': 'Contexto de la negociacion'}, {'name': 'OBJETIVO', 'desc': 'Tu objetivo ideal'}, {'name': 'CONTRAPARTE', 'desc': 'Perfil de la contraparte'}])

    # ─── CROSS-CUTTING: CREATIVIDAD ───

    qspec("creatividad_scamper_innovar", "Para generar innovacion sistematica sobre un producto, servicio o proceso usando SCAMPER. La creatividad con estructura produce mas ideas que la inspiracion sola.", "Facilitador de Innovacion con certificacion en Design Thinking y experiencia en talleres de ideacion para equipos de producto.", """SCAMPER aplicado:\n1. Sustituir: que puedo reemplazar?\n2. Combinar: que puedo juntar?\n3. Adaptar: que puedo copiar de otro dominio?\n4. Modificar/Magnificar: que puedo exagerar o cambiar?\n5. Poner otro uso: para que mas podria servir?\n6. Eliminar: que puedo quitar?\n7. Reorganizar/Revertir: que pasa si invierto el orden?\n8. Top 5 ideas priorizadas""", "Metodo:\n- SCAMPER: 7 tecnicas de innovacion sistematica\n- 3+ ideas por tecnica: forzar cantidad antes de calidad\n- Cross-pollination: las mejores ideas vienen de combinar tecnicas\n- Feasibility filter: de 21+ ideas, seleccionar top 5 por viabilidad × impacto", "Formato: 21+ ideas organizadas por tecnica + top 5 priorizadas.\nTono: creativo-estructurado.\nAudiencia: innovador o equipo de producto.\nAccion: prototipar la idea #1.", ["Min. 3 ideas por tecnica SCAMPER", "Las ideas son genuinamente diferentes entre si", "El top 5 tiene evaluacion de viabilidad", "Al menos 1 idea es no-obvia"], [{'name': 'OBJETO', 'desc': 'Producto, servicio o proceso a innovar'}, {'name': 'RESTRICCIONES', 'desc': 'Restricciones conocidas', 'opt': True}])

    # ─── CROSS-CUTTING: BIENESTAR ───

    qspec("bienestar_protocolo_anti_burnout", "Para disenar un protocolo personal que prevenga el burnout antes de que ocurra. El burnout no es un evento — es una acumulacion que se puede detectar y prevenir.", "Coach de Bienestar Ejecutivo con especializacion en prevencion de burnout y gestion de energia para profesionales de alto rendimiento.", """Protocolo anti-burnout:\n1. Early warning indicators: 5 senales personales de que te acercas al burnout\n2. Energy drains: las 3 actividades que mas te drenan\n3. Energy sources: las 3 actividades que mas te recargan\n4. Boundaries: limites no negociables (hora de cierre, dias off, etc.)\n5. Recovery protocol: que hacer cuando detectas las senales\n6. Check-in semanal: 3 preguntas de auto-diagnostico (2 min)""", "Metodo:\n- Prevention > recovery: detectar antes de que sea tarde\n- Personal indicators: cada persona tiene senales diferentes\n- Energy management > time management\n- Non-negotiable boundaries: proteger antes de necesitar", "Formato: protocolo personal + check-in semanal + recovery plan.\nTono: sereno, compasivo.\nAudiencia: profesional de alto rendimiento.\nAccion: hacer el primer check-in hoy.", ["Los early warning indicators son personales (no genericos)", "Los boundaries son especificos y no negociables", "El recovery protocol es ejecutable en 24h", "El check-in semanal cabe en 2 minutos"], [{'name': 'ROL', 'desc': 'Tu rol profesional'}, {'name': 'DRAINS', 'desc': 'Las 3 cosas que mas te drenan'}])

    # ─── CROSS-CUTTING: ESTRATEGIA ───

    qspec("estrategia_vision_3_horizontes", "Para definir tu estrategia personal o de negocio en 3 horizontes temporales: mantener, crecer, explorar. El futuro no se predice, se disena.", "Estratega de Innovacion con experiencia en Three Horizons Framework de McKinsey para empresas en transformacion.", """3 Horizontes:\n1. H1 — Mantener (0-12 meses): que funciona y hay que proteger\n2. H2 — Crecer (1-3 anos): que oportunidades explorar para escalar\n3. H3 — Explorar (3-5 anos): que apuestas disruptivas hacer\n4. Resource allocation: % de tiempo/dinero por horizonte (recomendado: 70-20-10)\n5. Metricas por horizonte: como medir progreso en cada uno\n6. Decision: que iniciar, que escalar, que matar""", "Metodo:\n- McKinsey Three Horizons: manage, grow, explore\n- 70-20-10: la mayoria del recurso en H1, la apuesta en H3\n- H3 kills H1: las disrupciones futuras reemplazan el core actual\n- Portfolio thinking: no todo tiene que funcionar, pero hay que apostar", "Formato: mapa de 3 horizontes + resource allocation + metricas.\nTono: estrategico, visionario.\nAudiencia: lider de estrategia o profesional planificando su carrera.\nAccion: definir 1 apuesta por horizonte.", ["Los 3 horizontes tienen contenido concreto", "El resource allocation esta definido", "Las metricas son diferentes por horizonte", "Hay al menos 1 apuesta disruptiva en H3"], [{'name': 'CONTEXTO', 'desc': 'Tu organizacion o carrera'}, {'name': 'HORIZONTE', 'desc': 'Horizonte temporal a planificar'}])

    qspec("estrategia_okr_personal_trimestral", "Para definir OKRs personales que conecten tu dia a dia con tus objetivos de largo plazo. Sin OKRs, trabajas duro sin saber si avanzas.", "OKR Coach con experiencia en implementacion de OKRs a nivel individual y de equipo para startups y corporaciones.", """OKR Personal Trimestral:\n1. Vision: donde quiero estar en 1 ano\n2. Objetivos (max 3): cualitativos, inspiradores, ambiciosos\n3. Key Results (2-3 por objetivo): cuantitativos, medibles, verificables\n4. Iniciativas: acciones concretas para mover cada KR\n5. Weekly check: como medir progreso semanal\n6. Scoring: como evaluar al final del trimestre (0.0-1.0)""", "Metodo:\n- Objective = inspiracional: que quiero lograr\n- Key Result = medible: como se que lo logre\n- 70% achievement = sweet spot: si logras 100%, eran poco ambiciosos\n- Alignment: mis OKRs conectan con la vision de largo plazo", "Formato: OKRs formateados + weekly check + scoring guide.\nTono: motivador-estructurado.\nAudiencia: profesional que quiere direccion.\nAccion: definir los OKRs de este trimestre.", ["Max 3 objetivos", "Cada KR es numerico y verificable", "Las iniciativas son accionables (no vagas)", "El weekly check cabe en 5 minutos"], [{'name': 'VISION', 'desc': 'Tu vision a 1 ano'}, {'name': 'TRIMESTRE', 'desc': 'Trimestre a planificar'}])

    # ─── CROSS-CUTTING: META ───

    qspec("meta_reverse_engineer_conversacion", "Para hacer ingenieria inversa de una conversacion con IA y extraer un SPEC reutilizable. El proceso de hoy construye el atajo de manana.", "Meta-Prompt Engineer con experiencia en extraccion de patrones de conversaciones para crear prompts reutilizables.", """Ingenieria inversa:\n1. Analizar historial completo de la sesion\n2. Identificar: objetivo real, inputs clave, decisiones, formato final\n3. Extraer el patron: que tipo de tarea fue, que metodo funciono\n4. Generar PROMPT A (Priming, max 200 palabras): contexto + rol + restricciones\n5. Generar PROMPT B (SPEC completo): [inputs] / [prompt] S-P-E-C / [checklist]\n6. Formatear ambos para copiar a text expander""", "Metodo:\n- Pattern extraction: encontrar la estructura reutilizable\n- Generalize: convertir el caso especifico en template parametrico\n- Test: el SPEC generado debe producir resultados comparables\n- Iterate: mejorar el SPEC con cada uso", "Formato: 2 prompts listos para text expander.\nTono: tecnico.\nAudiencia: tu yo futuro que necesitara hacer lo mismo.\nAccion: guardar ambos prompts en tu text expander.", ["El SPEC captura el patron (no el caso especifico)", "Los parametros permiten reusar en diferentes contextos", "El priming cabe en 200 palabras", "El SPEC tiene las 4 secciones completas"], [{'name': 'SESION', 'desc': 'Describe la sesion a reverse-engineer o pega el historial'}])

    qspec("meta_auditar_mis_prompts", "Para evaluar la calidad de tus propios prompts y mejorarlos sistematicamente. La mayoria de prompts que escribes estan al 40% de su potencial.", "Prompt Quality Auditor con experiencia en evaluacion y mejora sistematica de bibliotecas de prompts empresariales.", """Auditoria de prompts:\n1. Seleccionar 10 prompts que mas usas\n2. Evaluar cada uno contra la rubrica SPEC:\n   - Tiene Situacion clara? (contexto prospectivo)\n   - Tiene Pedido especifico? (arquetipo + entregable)\n   - Tiene Ejecucion definida? (metodo + protocolo)\n   - Tiene Criterio medible? (formato + exito)\n3. Score 1-10 por dimension\n4. Top 3 prompts a mejorar (mayor gap vs potencial)\n5. Versiones mejoradas de cada uno\n6. Before/after comparison""", "Metodo:\n- SPEC rubric: S + P + E + C como dimensiones de calidad\n- 80/20: mejorar el 20% de prompts que usas el 80% del tiempo\n- Before/after: la mejora debe ser medible\n- Test: ejecutar ambas versiones y comparar output", "Formato: auditoria de 10 prompts + 3 versiones mejoradas.\nTono: analitico, constructivo.\nAudiencia: tu mismo.\nAccion: reemplazar los 3 prompts mejorados en tu text expander.", ["Los 10 prompts mas usados estan evaluados", "El score por dimension es honesto", "Los 3 mejorados son significativamente mejores", "El before/after es evidente"], [{'name': 'PROMPTS', 'desc': 'Pega tus 10 prompts mas usados o describe lo que haces con IA'}])

    qspec("meta_crear_system_prompt_agente", "Para crear un system prompt robusto para un agente de IA que opera con autonomia. El system prompt es la constitucion del agente — define quien es, que puede y que jamas debe hacer.", "AI Agent Architect con experiencia en diseno de agentes autonomos con guardrails para operaciones empresariales.", """System Prompt de Agente:\n1. Identity: nombre, rol, personalidad, tono\n2. Capabilities: que puede hacer (scope positivo)\n3. Boundaries: que jamas debe hacer (scope negativo)\n4. Knowledge: de donde obtiene informacion\n5. Interaction protocol: como interactua con el usuario\n6. Output format: formato default de respuestas\n7. Guardrails: reglas de seguridad y etica\n8. Escalation: cuando pasar a un humano\n9. 5 few-shot examples""", "Metodo:\n- Constitution first: boundaries antes que capabilities\n- Personality calibration: el tono afecta la percepcion de competencia\n- Few-shot > instruction: mostrar el comportamiento deseado\n- Adversarial testing: intentar romper el agente antes de publicar", "Formato: system prompt completo listo para copiar.\nTono: tecnico.\nAudiencia: developer o prompt engineer.\nAccion: implementar el agente.", ["Las boundaries son explicitas y no negociables", "Los guardrails cubren safety y ethics", "Los 5 examples son representativos del uso real", "La escalacion a humano esta definida"], [{'name': 'AGENTE', 'desc': 'Nombre y funcion del agente'}, {'name': 'AUDIENCIA', 'desc': 'Quien usara el agente'}, {'name': 'AUTONOMIA', 'desc': 'Nivel de autonomia (semi, alto, total)'}])

    qspec("meta_taxonomia_prompts_organizar", "Para crear una taxonomia que organice cualquier biblioteca de prompts de forma navegable y escalable.", "Information Architect con experiencia en taxonomias de contenido y sistemas de clasificacion para bibliotecas digitales.", """Taxonomia de prompts:\n1. Categorias principales: max 10 (agrupacion por dominio)\n2. Sub-categorias: max 5 por categoria\n3. Tags transversales: dificultad, tipo de output, modelo recomendado\n4. Naming convention: formato consistente para claves\n5. Metadata por prompt: categoria, tags, params count, estimated tokens\n6. Navigation: como un usuario encuentra el prompt que necesita""", "Metodo:\n- MECE categories: mutuamente excluyentes, colectivamente exhaustivas\n- Flat > deep: max 2 niveles de profundidad\n- User-centric: organizar por lo que el usuario busca, no por como se creo\n- Scalable: la taxonomia debe funcionar con 100 y con 1000 prompts", "Formato: taxonomia completa + naming convention + navigation guide.\nTono: sistematico.\nAudiencia: curador de la biblioteca.\nAccion: aplicar la taxonomia a la biblioteca existente.", ["Las categorias son MECE", "Max 2 niveles de profundidad", "La naming convention es consistente", "La navegacion es intuitiva para un usuario nuevo"], [{'name': 'BIBLIOTECA', 'desc': 'Descripcion de la biblioteca a organizar'}, {'name': 'TAMANO', 'desc': 'Numero aproximado de prompts'}])

    # ─── GAPS: investigacion +1, escritura +1, data +4 ───

    qspec("investigacion_analisis_bibliometrico", "Para mapear el panorama academico de un campo: quienes investigan, que publican, donde se concentra la produccion, y cuales son las fronteras del conocimiento.", "Bibliometrista con experiencia en analisis de produccion cientifica, redes de citacion y mapeo de fronteras de conocimiento.", """Analisis bibliometrico:\n1. Definir campo y periodo de analisis\n2. Volumen de publicaciones por ano (tendencia)\n3. Top autores y sus redes de colaboracion\n4. Top journals y conferencias\n5. Keyword co-occurrence: temas emergentes\n6. Citation analysis: papers mas influyentes\n7. Research gaps: que NO se esta investigando""", "Metodo:\n- Bibliometrics: cuantificar la produccion cientifica\n- Co-citation analysis: papers que se citan juntos = relacion tematica\n- Keyword emergence: temas cuya frecuencia crece aceleradamente\n- White spaces: donde hay poca publicacion = oportunidad", "Formato: panorama bibliometrico con graficos + top papers + gaps.\nTono: academico-estrategico.\nAudiencia: investigador o decision-maker que necesita state-of-the-art.\nAccion: usar como base para tu investigacion.", ["El volumen temporal muestra tendencia", "Los top autores y journals estan identificados", "Los temas emergentes estan senalados", "Los research gaps son oportunidades concretas"], [{'name': 'CAMPO', 'desc': 'Campo o tema de investigacion'}, {'name': 'PERIODO', 'desc': 'Periodo de analisis (ultimos 5, 10, 20 anos)'}])

    qspec("escritura_manual_procedimientos", "Para documentar un procedimiento operativo de forma que cualquier persona pueda seguirlo sin ambiguedad. El mejor manual es el que no necesita explicacion adicional.", "Technical Writer Senior con experiencia en documentacion de procesos para ISO 9001 y equipos de operaciones.", """Manual de procedimientos:\n1. Titulo y version\n2. Proposito: por que existe este procedimiento\n3. Alcance: cuando aplica y cuando NO\n4. Prerequisitos: que necesitas antes de empezar\n5. Pasos: numerados, con 1 accion por paso\n6. Decision points: si X, ir a paso Y; si no, ir a paso Z\n7. Screenshots o diagramas donde aplique\n8. Troubleshooting: 5 problemas comunes y solucion\n9. Responsable de actualizacion""", "Metodo:\n- 1 action per step: nunca 2 acciones en 1 paso\n- Show don't tell: screenshots > descripciones largas\n- Test with novice: alguien sin experiencia debe poder seguirlo\n- Version control: cada cambio tiene fecha y responsable", "Formato: manual listo para publicar internamente.\nTono: claro, sin ambiguedad.\nAudiencia: cualquier persona que deba ejecutar este procedimiento.\nAccion: publicar y testear con alguien nuevo.", ["Cada paso tiene 1 sola accion", "Los decision points estan claros", "El troubleshooting cubre los 5 problemas mas comunes", "Un novato puede seguirlo sin ayuda"], [{'name': 'PROCEDIMIENTO', 'desc': 'Procedimiento a documentar'}, {'name': 'AUDIENCIA', 'desc': 'Quien ejecutara este procedimiento'}])

    qspec("data_pivot_table_analisis", "Para disenar y ejecutar analisis con tablas pivote que revelen patrones ocultos en los datos. La pivot table es el microscopio del analista.", "Data Analyst con experiencia en Excel avanzado y pivot table analysis para reporting financiero y operacional.", """Pivot Table Analysis:\n1. Pregunta de negocio a responder\n2. Dataset: que columnas, que filas, que tipo de datos\n3. Configuracion: filas, columnas, valores, filtros\n4. Agregaciones: suma, promedio, conteo, % del total\n5. Top insights: que patrones revela la pivot\n6. Drill-down: donde profundizar basado en los hallazgos""", "Metodo:\n- Question-first: la pregunta define la configuracion, no al reves\n- Start simple: 2 dimensiones, 1 metrica. Luego agregar complejidad\n- Compare: meses, regiones, productos lado a lado\n- So-what: cada patron con implicacion de negocio", "Formato: configuracion de pivot + insights + drill-down recommendations.\nTono: analitico.\nAudiencia: analista o decision-maker.\nAccion: crear la pivot y extraer insights.", ["La configuracion responde la pregunta de negocio", "Los insights son accionables", "El drill-down identifica donde profundizar", "La pivot es reproducible con los datos disponibles"], [{'name': 'PREGUNTA', 'desc': 'Pregunta de negocio'}, {'name': 'DATOS', 'desc': 'Columnas y tipo de datos disponibles'}])

    qspec("data_anomaly_detection_manual", "Para identificar anomalias y outliers en un dataset sin herramientas complejas. Los outliers son o errores (limpiar) o insights (investigar).", "Estadistica Aplicada con experiencia en deteccion de anomalias para fraude, calidad de datos y analisis operacional.", """Deteccion de anomalias:\n1. Definir que es 'normal' para cada variable (baseline)\n2. Metodos de deteccion: Z-score, IQR, visual (boxplot descrito)\n3. Clasificar anomalias: error de datos / evento real / fraude potencial\n4. Para cada anomalia: investigar causa\n5. Decision: limpiar, conservar, o escalar\n6. Automated alerts: criterios para deteccion futura""", "Metodo:\n- Statistical: Z-score > 3 o IQR × 1.5\n- Visual: boxplot para identificar, scatter para contextualizar\n- Domain knowledge: lo estadisticamente anomalo puede ser normal en el dominio\n- Classification: error vs insight vs investigar", "Formato: lista de anomalias + clasificacion + acciones.\nTono: analitico.\nAudiencia: analista de datos.\nAccion: investigar las anomalias tipo 'evento real'.", ["El baseline de normalidad esta definido", "Las anomalias estan clasificadas por tipo", "Cada anomalia tiene causa investigada", "Los criterios de alerta automatica estan definidos"], [{'name': 'DATASET', 'desc': 'Descripcion del dataset'}, {'name': 'VARIABLES', 'desc': 'Variables a analizar'}])

    qspec("data_storytelling_presentation", "Para construir una presentacion donde los datos cuentan una historia que persuade y mueve a la accion. Los datos sin narrativa son ignorados.", "Data Storytelling Expert con experiencia en presentaciones basadas en datos para C-levels y boards.", """Data Storytelling Presentation:\n1. Insight principal: la conclusion en 1 oracion\n2. Arco narrativo: contexto > descubrimiento > implicacion > accion\n3. Cifras protagonistas: 3-5 numeros que soportan la historia\n4. Visualizaciones: 1 grafico por insight (tipo optimo por dato)\n5. Comparaciones: benchmark, antes/despues, proyeccion\n6. Call to action: que decision tomar basada en los datos""", "Metodo:\n- Start with insight, not with data\n- 1 chart per insight: cada grafico cuenta 1 cosa\n- Annotate: el grafico sin anotacion es ambiguo\n- So-what: cada slide responde 'y esto que significa para nosotros?'", "Formato: outline de presentacion con visualizaciones + notas.\nTono: persuasivo, basado en evidencia.\nAudiencia: {{AUDIENCIA}}.\nAccion: tomar la decision que los datos soportan.", ["El insight principal cabe en 1 oracion", "Cada visualizacion tiene anotaciones", "Las comparaciones dan contexto a los numeros", "El CTA es claro y fundamentado"], [{'name': 'DATOS', 'desc': 'Datos o hallazgos a presentar'}, {'name': 'AUDIENCIA', 'desc': 'Quien ve la presentacion'}, {'name': 'DECISION', 'desc': 'Que decision debe tomarse'}])

    qspec("data_sql_basico_consulta", "Para construir queries SQL basicas que extraigan la informacion que necesitas sin depender de un data analyst. SQL basico es la alfabetizacion de datos.", "Data Analyst con experiencia en SQL didactico para profesionales no-tecnicos que necesitan acceso a datos.", """SQL Query basica:\n1. Pregunta en lenguaje natural: que quiero saber\n2. Tablas involucradas y sus columnas relevantes\n3. Query paso a paso:\n   - SELECT: que columnas quiero ver\n   - FROM: de que tabla\n   - WHERE: que filtros aplico\n   - GROUP BY: como agrupo\n   - ORDER BY: como ordeno\n   - LIMIT: cuantos registros\n4. Explicacion linea por linea\n5. Variantes para preguntas relacionadas""", "Metodo:\n- Natural language > SQL: primero la pregunta, despues la query\n- Build incrementally: SELECT primero, luego WHERE, luego GROUP BY\n- Verify: query de conteo para validar que los filtros son correctos\n- Comment: cada seccion con comentario explicativo", "Formato: query SQL + explicacion + variantes.\nTono: pedagogico.\nAudiencia: profesional no-tecnico.\nAccion: ejecutar la query.", ["La query responde la pregunta de negocio", "Cada linea tiene explicacion", "Las variantes cubren preguntas relacionadas", "La query de verificacion esta incluida"], [{'name': 'PREGUNTA', 'desc': 'Que quieres saber de los datos'}, {'name': 'TABLAS', 'desc': 'Tablas y columnas disponibles'}])
